steps:
  - name: ":hammer: Build"
    command: scripts/build
    artifact_paths: "dist/**.gz"
    plugins:
      - docker-compose#v4.14.0:
          config: docker-compose.yml
          cli-version: 2
          run: yaml2json
