#!/bin/bash
set -e

echo "Building yaml2json 💨"
echo

rm -rf dist
mkdir -p dist

for goos in {darwin,linux}; do
  for goarch in {amd64,arm64}; do
    echo "Compiling for ${goarch} ${goos}"
    GOOS="${goos}" GOARCH="${goarch}" go build -o "dist/yaml2json-${goos}-${goarch}" -ldflags '-s -w' ./cmd/yaml2json
    chmod +x "dist/yaml2json-${goos}-${goarch}"
    echo "👍  dist/yaml2json-${goos}-${goarch}"
    gzip -k "dist/yaml2json-${goos}-${goarch}"
    echo
  done
done

echo ""
echo "All done! ✅"
